/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-tint": "#494bd6",
        "outline-variant": "#c7c4d7",
        "on-tertiary-fixed": "#0f0069",
        "on-tertiary-fixed-variant": "#3323cc",
        "on-secondary-container": "#fffbff",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "secondary": "#8127cf",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#fffbff",
        "surface-container": "#eceef0",
        "outline": "#767586",
        "secondary-container": "#9c48ea",
        "on-secondary-fixed": "#2c0051",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "secondary-fixed-dim": "#ddb7ff",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#c0c1ff",
        "on-primary-container": "#fffbff",
        "primary": "#4648d4",
        "on-secondary-fixed-variant": "#6900b3",
        "tertiary-fixed": "#e2dfff",
        "primary-container": "#6063ee",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "tertiary": "#4b41e1",
        "on-surface-variant": "#464554",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#c3c0ff",
        "on-surface": "#191c1e",
        "tertiary-container": "#645efb",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#f0dbff",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed": "#07006c",
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          500: '#4648d4', // Mapped brand-500 to primary for reuse
          600: '#2f2ebe',
          900: '#191c1e',
        }
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
